### ISSUE TITLE
Argument of type 'SPHttpClientConfiguration' is not assign able to parameter of type 'SPHttpClientConfiguration'.

### ISSUE THREAD

**Issue by cohenpts** [SharePoint/sp-dev-docs#911]
#### Category
- [ ] Question
- [ ] Typo
- [ X ] Bug
- [ ] Additional article idea

Unable to Build my SharePoint solution.
When building each of my webparts has the error
```
"Argument of type 'SPHttpClientConfiguration' is not assign able to parameter of type 'SPHttpClientConfiguration'."
```
all my sharepoint module imports are the same in all webparts:
```
import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http';
import { Version, Environment, EnvironmentType } from '@microsoft/sp-core-library';
import {
  BaseClientSideWebPart,
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-webpart-base';
```

Package,json
```
  "dependencies": {
    "@microsoft/sp-core-library": "~1.3.0",
    "@microsoft/sp-http": "^1.3.0",
    "@microsoft/sp-webpart-base": "~1.3.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "sp-client-custom-fields": "^1.3.4"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.3.0",
    "@microsoft/sp-module-interfaces": "~1.3.0",
    "@microsoft/sp-webpart-workbench": "~1.3.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "~3.9.1",
    "tslint": "^5.7.0",
    "url-loader": "^0.5.9"
  }
```

Tried removing node_modules and installing a few times and still experiencing the same issue.
thanks in advance.

**Comment by waldekmastykarz** [comment]
Could you please check two things?

1. Remove `@microsoft/sp-http` from the dependencies. If you create a new project using the SPFx generator, it isn't listed there directly
1. Temporarily remove `sp-client-custom-fields` from your project and see if it helps. It seems that the currently available package has been built using an older version of the SharePoint Framework and it might be incompatible with the v1.3 you're using in your project

**Comment by cohenpts** [comment]
@waldekmastykarz thanks for the quick response.

Removed both sp-http and sp-client-custom-fields.
Now I am getting the error.
```
Cannot find module '@microsoft/sp-http'
```
Do I need to have a special reference declaration when doing
```
import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http';
```

**Comment by waldekmastykarz** [comment]
@cohenpts have you removed `@microsoft/sp-http` from package.json or did you run `npm uninstall @microsoft/sp-http --save-dev`?

What I meant by removing is, to remove the reference to it from package.json and restoring dependencies.

**Comment by cohenpts** [comment]
I copied the node modules folder from a new yeoman scaffold and haven't been able to reproduce the issue.

Appreciate the help

**Comment by waldekmastykarz** [comment]
@cohenpts if the issue is solved, could you please close it? Thanks! 🙂

**Comment by iclanton** [comment]
It's been a few days, so we're going to go ahead and close this issue. If you see this again, can you reopen this? Thanks!

**Comment by runmotion** [comment]
Hi, I have the same problem. What can I do to solve the issue? Copying the modules folder from a new yeoman scaffold does not work.

**Comment by waldekmastykarz** [comment]
@runmotion have you by any chance updated your project recently? If so, try running `npm dedupe` and see if it helps.

**Comment by aslanovsergey** [comment]
@waldekmastykarz `npm dedupe` helped when updated my project to 1.7 but later when I transformed it into -plusbeta replacing packages names in package.json the `npm dudupe` command didn't help anymore

**Comment by waldekmastykarz** [comment]
After replacing package versions in package.json, did you remove the package-lock.json file and run `npm install` again?

**Comment by aslanovsergey** [comment]
Yup, I did! 

Sergey

**Comment by waldekmastykarz** [comment]
Did you also remove `node_modules`?

**Comment by aslanovsergey** [comment]
Sure

**Comment by kodofix** [comment]
@waldekmastykarz  I just update dependencies to 1.7.1 version and I had the same problem with @microsoft/sp-http but npm dedupe actually works for me and fix problem. 

Thanks for help.

**Comment by PieterHeemeryck** [comment]
> Could you please check two things?
> 
> 1. Remove `@microsoft/sp-http` from the dependencies. If you create a new project using the SPFx generator, it isn't listed there directly
> 2. Temporarily remove `sp-client-custom-fields` from your project and see if it helps. It seems that the currently available package has been built using an older version of the SharePoint Framework and it might be incompatible with the v1.3 you're using in your project

The first suggestion resolved my issue. SPFx 1.8.2, node v10 (copied over a project, did not start a new one using yeoman).
