### ISSUE TITLE
Does not work with 1.6  

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#2834]
I get "Cannot find module "itRequestsStrings" (it is in mystrings.d.ts)
If I rem the "import * as strings from 'itRequestsStrings';" I get "Property 'dataTable' does not exist on type 'JQuery&lt;HTMLElement&gt;'. Did you mean 'DataTable'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56fb9ec-59c2-413f-eaa2-e84abfb30211
* Version Independent ID: ca610020-3018-fd78-1da5-7f00fed5b04f
* Content: [Migrate jQuery and DataTables solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The dataTable mean DataTable from jquery.dataTables.min js, we do not need to change it. What you need is change the itRequestsStrings after creating the project.

Note: you maybe need to run` **npm i jquery**` and `**npm i moment**`.  

I run SPFx 1.6 and follow the docs, every thing is OK. Before running the code, donot forget to create the list "IT Requests"

**Comment by aaronmi** [comment]
With spfx 1.7, I got the following with both ItRequestsWebPart.ts and moment-plugin.ts.
"error TS2339: Property 'render' does not exist on type '(param?: Settings) => DataTable'.

**Comment by aaronmi** [comment]
Changed code to ($.fn.DataTable as any).render.moment('YYYY/MM/DD'). Got runtime error:

ItRequestsWebPart.ts:72 Uncaught (in promise) TypeError: Cannot read property 'render' of undefined
    at ItRequestsWebPart.render (ItRequestsWebPart.ts:72)
    at ItRequestsWebPart.t._renderWithAccessibleTitle (sp-webpart-workbench-assembly_en-us_cee2ed9196d873e2374ab4945906bf2a.js:577)
    at sp-webpart-workbench-assembly_en-us_cee2ed9196d873e2374ab4945906bf2a.js:577
