### ISSUE TITLE
Getting Errors after upgrade to SPFx 1.5.0

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2047]
_From @bhanuprakash857 on June 14, 2018 13:29_

I'm trying to upgrade my webpart from 1.1.0 to 1.5.0. I have upgraded the versions to 1.5.0  after that ,while runing gulp serve i'm getting below error.
gulp serve

![image](https://user-images.githubusercontent.com/12428545/41414705-6b2c005a-7004-11e8-8afd-382db7385b91.png)

Errors:
[18:53:50] Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(15,22): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
[18:53:50] Error - typescript - node_modules\@types\react\index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
[18:53:50] Error - typescript - src\webparts\caNewsAggregator\app\app-module.ts(10,33): error TS2345: Argument of type 'typeof HomeController' is not assignable to parameter of type 'Injectable<IControllerConstructor>'.

_Copied from original issue: SharePoint/sp-dev-fx-webparts#536_

**Comment by VesaJuvonen** [comment]
_From @JayakumarB on June 14, 2018 13:40_

Hi @bhanuprakash857 ,

May be one of the dependency for HttpClientResponse not loaded properly, can you please try to delete the node_modules in project folder and re-install it again using the `npm install` command and check.

**Comment by VesaJuvonen** [comment]
_From @bhanuprakash857 on June 14, 2018 14:54_

Hi @JayakumarB ,

Thank you for the reply.I have removed the node_modules and ran the `npm install` command. Still i'm getting the same errors.

**Comment by VesaJuvonen** [comment]
As this is NOT around any samples in the this repository, moving this discussion to the sp-dev-docs repository like noted in the issue template.

"Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster."

**Comment by bhanuprakash857** [comment]
Package.json
![image](https://user-images.githubusercontent.com/12428545/41579021-b1e40e64-73b2-11e8-84b8-a74bfaaa66b1.png)

I'm upgrading my SPFx webpart to 1.5.0 and upgraded the app modules from 1.1.0 to 1.5.0
I'm getting below errors. Could any one help me to fix this issues

![image](https://user-images.githubusercontent.com/12428545/41579051-e005ecc2-73b2-11e8-8aad-61aab039d513.png)

Please find the realted Article information: https://github.com/SharePoint/sp-dev-docs/issues/690

**Comment by vsoderholm** [comment]
Possible solution #2093

**Comment by VesaJuvonen** [comment]
Possible fix with upcoming 1.5.1, let's double check when it's out.

**Comment by VesaJuvonen** [comment]
This should be now addressed with the 1.5.1 release, so would request to validate the situation with following. Here are short release notes for 1.5.1 release - https://twitter.com/SharePoint/status/1011689501213757441.

**Comment by RiddhiKarani** [comment]
i m still seeing this issue with 1.5.1 additionally see below errors - 

/node_modules/@microsoft/sp-http/dist/index-internal.d.ts(180,22): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
  Property 'body' is missing in type 'HttpClientResponse'.
/node_modules/@microsoft/sp-page-context/dist/index-internal.d.ts(134,23): error TS2304: Cannot find name 'AzureActiveDirectoryInfo'.
/node_modules/@microsoft/sp-page-context/dist/index-internal.d.ts(536,21): error TS2304: Cannot find name 'O365GroupAssociation'.
TypeScript: 3 semantic errors
TypeScript: emit succeeded (with errors)
[16:43:25] Finished 'tsc' after 7.78 s

i have deleted the old node modules folder and did npm install but still see the above errors

**Comment by RiddhiKarani** [comment]
@VesaJuvonen  kindly suggest

**Comment by jpalo** [comment]
I'm also seeing this after updating from 1.4.1 to 1.5.1. Troubleshooting now and will get back after I figure out the cause.
