### ISSUE TITLE
Duplicate Entries (Modules) - Typescript

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#296]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Hello. I'm getting some duplicate entries after upgrade from DROP 4 to 6. Anyone had this kind of problem?, the original project is in: https://github.com/jtlivio/jl-spfx-project-webparts

Thanks for helping.

#### Steps attempted

1. Upgrade in Windows
2. Follow DROP 6 Documentation
3. Deleted node_modules
4. ```npm i```

#### Expected or Desired Behavior
Should build

#### Observed Behavior
```
Build target: DEBUG
[21:45:29] Using gulpfile ~\SPFx\jl-spfx-project-webparts\gulpfile.js
[21:45:29] Starting gulp
[21:45:29] Starting 'default'...
[21:45:29] Starting subtask 'pre-copy'...
[21:45:29] Finished subtask 'pre-copy' after 13 ms
[21:45:29] Starting subtask 'copyStaticAssets'...
[21:45:29] Starting subtask 'sass'...
[21:45:30] Finished subtask 'sass' after 891 ms
[21:45:30] Starting subtask 'tslint'...
[21:45:30] Starting subtask 'typescript'...
[21:45:30] [typescript] Using custom version: 2.0.10
[21:45:31] Finished subtask 'copyStaticAssets' after 1.72 s
[21:45:36] Error - typescript - node_modules\@types\core-js\index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.
[21:45:36] Error - typescript - node_modules\@types\core-js\index.d.ts(867,13): error TS2300: Duplicate identifier 'Promise'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(41,14): error TS2300: Duplicate identifier 'RequestInfo'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(42,15): error TS2300: Duplicate identifier 'Request'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(61,11): error TS2300: Duplicate identifier 'Request'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(78,6): error TS2300: Duplicate identifier 'RequestMode'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestCredentials'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestCache'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(84,15): error TS2300: Duplicate identifier 'Response'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
[21:45:36] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(109,6): error TS2300: Duplicate identifier 'ResponseType'.
[21:45:36] Error - typescript - src\webparts\spCrud\SpCrudWebPart.ts(259,12): error TS2322: Type 'Promise<void>' is not assignable to type 'Promise<T>'.
[21:45:36] Error - typescript - typings\es6-promise\es6-promise.d.ts(12,15): error TS2300: Duplicate identifier 'Promise'.
[21:45:36] Error - typescript - typings\es6-promise\es6-promise.d.ts(43,16): error TS2300: Duplicate identifier 'Promise'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(8,15): error TS2300: Duplicate identifier 'Request'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(22,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'HeadersInit', but here has type 'string[] | Headers | { [index: string]: string; }'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(24,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'RequestMode', but here has type 'string | "same-origin" | "navigate" | "no-cors" | "cors"'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(25,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'RequestCredentials', but here has type 'string | "same-origin" | "omit" | "include"'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(26,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'RequestCache', but here has type 'string | "default" | "no-store" | "reload" | "no-cache" | "force-cache" | "only-if-cached"'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(36,14): error TS2300: Duplicate identifier 'RequestMode'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(37,14): error TS2300: Duplicate identifier 'RequestCredentials'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(38,14): error TS2300: Duplicate identifier 'RequestCache'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(40,15): error TS2300: Duplicate identifier 'Headers'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(58,15): error TS2300: Duplicate identifier 'Response'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(71,14): error TS2300: Duplicate identifier 'ResponseType'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(74,2): error TS2687: All declarations of 'status' must have identical modifiers.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(76,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'HeadersInit', but here has type 'HeaderInit'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(80,14): error TS2300: Duplicate identifier 'BodyInit'.
[21:45:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(81,14): error TS2300: Duplicate identifier 'RequestInfo'.
[21:45:36] Finished subtask 'tslint' after 6.37 s
[21:45:36] Error - 'typescript' sub task errored after 6.52 s
 "TypeScript error(s) occurred."
[21:45:36] 'default' errored after 7.48 s
[21:45:36]
[21:45:37] ==================[ Finished ]==================
```

#### Final build steps

```
[21:45:38] Project jlivio-spfx-webparts version: 0.0.1
[21:45:38] Build tools version: 0.11.1
[21:45:38] Node version: v6.9.1
[21:45:38] Total duration: 13 s
[21:45:38] Task errors: 32
```

#### Steps to Reproduce

1. Import a project from DROP 4 (Created on Linux) to Windows
2. Follow all procedures to Upgrade to DROP 6
3. ```gulp```

**Comment by chakkaradeep** [comment]
Couple of things:

1. You said you imported a project that you created in Linux to Windows. This means, you will need to run 'npm install' again as there are some platform specific packages that could be broken. Just delete node_modules folder and run npm install again.

2. Check the typescript version what you are pulling as well just to make sure it is 2.x.

**Comment by jamir0** [comment]
Hi,
have the same issue. conflicts between @types/isomorphic-fetch & @types/whatwg-fetch. 
appears after update react@15.4.2 and the latest  version of @types/react. 
Also im using redux, apollo-client, react-apollo. 
ps. updating typescript version from 2.0.10 to 2.2.0 didn't solve the problem.

**Comment by chakkaradeep** [comment]
@jamir0 If you have upgraded and types installed, can you delete everything under the typings/ folder except @ms folder?

**Comment by jamir0** [comment]
@chakkaradeep had deleted all other td from ./typings except @ms folder. it didnt help. still the same errors:
```
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(6,14): error TS2300: Duplicate identifier 'RequestContext'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(14,14): error TS2300: Duplicate identifier 'RequestMode'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(15,14): error TS2300: Duplicate identifier 'RequestCredentials'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(16,14): error TS2300: Duplicate identifier 'RequestCache'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(20,14): error TS2300: Duplicate identifier 'ResponseType'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(22,14): error TS2300: Duplicate identifier 'HeaderInit'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(23,14): error TS2300: Duplicate identifier 'BodyInit'.
Error - typescript - node_modules\@types\isomorphic-fetch\index.d.ts(24,14): error TS2300: Duplicate identifier 'RequestInfo'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(6,15): error TS2300: Duplicate identifier 'Request'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(29,6): error TS2300: Duplicate identifier 'RequestContext'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(37,6): error TS2300: Duplicate identifier 'RequestMode'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(39,6): error TS2300: Duplicate identifier 'RequestCredentials'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(40,6): error TS2300: Duplicate identifier 'RequestCache'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(48,15): error TS2300: Duplicate identifier 'Headers'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(59,15): error TS2300: Duplicate identifier 'Body'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(82,6): error TS2300: Duplicate identifier 'ResponseType'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(90,14): error TS2300: Duplicate identifier 'HeaderInit'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(91,14): error TS2300: Duplicate identifier 'BodyInit'.
Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(92,14): error TS2300: Duplicate identifier 'RequestInfo'.
```

**Comment by dodedodo33** [comment]
Just scrolled by looking for a solution for another project. Thought to leave some comment on this. It seems that typescript now includes the fetch type definitions itself. So this is giving duplicate issues when the definitelytyped definitions are added as well. You could uninstall the whatwg-fetch and isomorphic-fetch typings (node uninstall @types/whatwg-fetch @types/isomorphic-fetch). Hopefully it resolves the issue for you.

**Comment by iclanton** [comment]
I'm going to close this issue since the solution is to remove the whatwg-fetch typings. If anyone else has an issue with this, feel free to re-open this issue or file another issue.
