### ISSUE TITLE
Fabric TeachingBubbles control broken after SPFX 1.8.2 upgrade

### ISSUE THREAD

**Issue by harrychen1** [SharePoint/sp-dev-docs#3957]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

After we upgrade SPFx from 1.7.1 to 1.8.2, the TeachingBubbles control is not working as expected. The previous behaviors is you could click button to display the Callout and then click the "X" to close it. 

However, there is error during the upgrade and we have to change the code to compile the code. 
The compilation error is gone but Callout is always displayed and it cannot be closed. The message is displayed on the main screen not in the Callout screen.

I've placed the code before the upgrade and after upgrade here.
https://sharepointconnoisseur.blogspot.com/2019/05/fabric-teachingbubbles-control-broken.html

I'm still researching the solution. Anyone has the same issue? Any suggestion is highly appreciated.

Thanks.

**Comment by harrychen1** [comment]
Issue has been resolved. Close the case.
