### ISSUE TITLE
Error - typescript - src/HelperTS/Common.ts(6,4): error TS2304: Cannot find name 'SP'.

### ISSUE THREAD

**Issue by nisarhukrani** [SharePoint/sp-dev-docs#1427]
![image](https://user-images.githubusercontent.com/33654481/36893214-2e0e109c-1e2d-11e8-988d-b91299f4767f.png)

Hi,
     i have install Sharepoint in my soilution using 
   npm install sharepoint --save.
  npm install @types/sharepoint --save.
When i'm trying to use SP it is giving me the error as  Cannot find name 'SP'. Previously it is working fine for me when i was using SPFx version 1.4.0. But now i'm using SPFx version 1.4.1 and getting the above error.

This is my package.json
![image](https://user-images.githubusercontent.com/33654481/36893893-b7b8ea90-1e2f-11e8-98a3-cc5c0a13d467.png)

 
Can anyone suggest me what need to done so that it will work in  SPFx version 1.4.1.

Thanks in Advance.

**Comment by VesaJuvonen** [comment]
Hi @nisarhukrani - this package 'sharepoint' is not controlled by Microsoft and apparently has not been updated for last 6 years, so would not recommend using that in your SharePoint Framework solutions.

Package details at npm - https://www.npmjs.com/package/sharepoint. 

For the REST operations in the context of SharePoint, we recommend using out-of-the-box classes provided by Microsoft. Please have a look at following step-by-step guidance - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part. 

If you have any specific questions or gaps around provided capabilities, please do let us know, but closing this as you should not definitely use 'sharepoint' package with SPFx.

**Comment by VesaJuvonen** [comment]
@nisarhukrani - on the version difference. There might have been some changes or overlap with the 1.4.0 to 1.4.1, but since this package really is out of date, would not recommend spending time on investigating how things work, as it should not be used with SPFx for basic REST operations.

Curious though on hearing more on possible reasons why it was used - if there's any gaps on the capabilities which Microsoft is providing. Thx.
